### ISSUE TITLE
Manual GeoPoint not working

### ISSUE THREAD

**Issue by tklecka** [OpenDroneAT/OpenDrone-App#14]
**Describe the bug**
If i create a new flightplan, save it and then edit it and want to change a geopoint mauel it will not be changed

**To Reproduce**
1. Create Flight plan and save it
2. Click on 'Settings'
3. change the first geopoint (e.g. from 48.5 to 48.0)
4. save it
5. 😢

**Expected behavior**
I expect the Geopoint to be saved

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [Android 9]
 - Version [1.0]

**Additional context**
-

**Comment by michaelhitzker** [comment]
done
