### ISSUE TITLE
Crashes when I click on Fly

### ISSUE THREAD

**Issue by tklecka** [OpenDroneAT/OpenDrone-App#15]
**Describe the bug**
App crashes when I click on Fly

**To Reproduce**
1. Start App
2. Click on the hamburger
3. Click on 'Fly'
4. 😢

**Expected behavior**
The Fly GUI should open

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 2]
 - OS: [Andoid 9]
 - Version [1.0]

**Additional context**
-

**Comment by tklecka** [comment]
at.opendrone.opendrone.CustomFontTextView.changeFont
CustomFontTextView.java, line 27

**Comment by michaelhitzker** [comment]
done
